### PR TITLE
add deadgrep-(forward|backward)-filename

### PR DESCRIPTION
**Pull request by travisjeffery**
Adds some commands and binds for moving to files.

### CODE REVIEW

**Comment by travisjeffery** [comment]
@Wilfred

**Comment by thomasf** [comment]
this is good because I want to skip the files alltogether when browsing next/prev.. I think I want a binding to display the file in other windows without switching to it as well but that doesn't necessarily need to be in the package.

**Comment by Wilfred** [comment]
What a great feature! I really like it :)

Thanks, merged in cefe36c.

**Comment by Wilfred** [comment]
@thomasf if you only want to navigate between matches, ignoring files, try `deadgrep-forward-match` (bound to `N`).

If you have other features you'd like, feel free to open an issue too.

**Pull request closed without merging**
