### PR TITLE
Add `deadgrep-next-` and `deadgrep-previous-matching-text`.

### LINKED ISSUE #28: [Feature Request] ability to loop through search hits
full-ack.el provides this functionality and it makes it really easy to do repo wide refactor

1) make a search
2) jump to first hit in the search result buffer
3) start to record a macro <kbd>C-x (</kbd>
4) Press enter (this will take you to the file and put the cursor at the start of the match)
5) do the refactoring
6) jump back to the search result buffer
7) move to the nex hit
8) finish the macro <kbd>C-x (</kbd>

The macro can now be applied for the rest of the hits using <kbd>C-x e</kbd>. The important functionality that makes this possible is the ability to move to the **start** of next search hit.

### PR DESCRIPTION
**Pull request by leungbk**
Closes #28.

### CODE REVIEW

**Comment by leungbk** [comment]
Ah, just realized I wasn't handling consecutive matches properly (in addition to me misunderstanding how ERT worked). Sorry, I'll get this done soon-ish.

**Comment by Wilfred** [comment]
Thanks for the PR! I think the reason the test is passing in ERT is because you're doing a search. Whilst you're stepping through (and emacs is waiting for input), the search is running and populating the result buffer. If the test runs without a debugger, it doesn't get a chance to display results.

I suggest you manually create a results buffer without doing a search. Let me know if you need a hand :)

**Comment by leungbk** [comment]
Thanks for your response! Yeah, I came to the same conclusion. But in addition to that, since my current patch doesn't handle consecutive matches as I would like*, I'm thinking of doing the following: use `pcre2el` or something similar to convert the user's `ripgrep` input to an equivalent Elisp regexp; and use `re-search-forward/backward` with this Elisp regexp, checking to see if the putative match also lies in a region reported by `ripgrep` as matching text.

My only concern is whether or not `pcre2el` captures enough of `ripgrep`'s regexp syntax. Do you expect this to be a problem?



\* such as searching for `abc` in a buffer with `abcabc`, where ideally `deadgrep-next-matching-text` should be able to land on either instance of `a`; with my current patch, I land only on the first `a`, and `ripgrep`'s match coloring applies throughout `abcabc`, so I can't selectively apply a text property to only the two `a`'s without doing another search within Emacs.

**Comment by Wilfred** [comment]
OK, I've added a command `deadgrep-next-match` in 3f372c1. This doesn't handle the consecutive match problem, but it works otherwise.

I think it would be very reasonable for us to request an rg argument that doesn't combine colour sequences. I don't think pcre2el is a good approach here, because PCRE can't be perfectly converted to elisp regexps, and rg doesn't use PCRE syntax exactly anyway.

One kludge might be to look at the average length of matches, and if any are 2x or longer, split them up. This would handle plain text searches and very simple regexps. It's not ideal -- feel free to open an issue to discuss this.

I'm going to close this since we now have a basic implementation, but thanks again for the PR :)

**Pull request closed without merging**
